spring:
  aop:
    proxyTargetClass: true
  application:
    name: api-gateway

# Define the port where the API gateway server would be running
server:
  port: 8765

# Define the Eureka server that handles service registration
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

zuul:
  add-host-header: true
  add-proxy-headers: true
  sensitive-headers:
  routes:
    dummy-service: 
      path: /dummy/**
    ui-service:
      path: /ui/**
      stripPrefix: false
    resource-service: /res/** 
    biz-service: /biz/**
    product-service: /product/**
    uaa-service:
      path: /uaa/**
      stripPrefix: false

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: /oauth/authorize
      scope: read, write
    resource:
      user-info-uri: ${auth-server}/me
auth-server: http://localhost:9999/uaa

logging:
  level.org.springframework.security: DEBUG

---

spring:
  profiles: docker

server:
  port: ${SERVICE_PORT}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${REGISTRY_URL}
      


logging:
  level:
    ROOT: INFO
    se.callista: INFO

    # Get info regarding connection to the cofig server and retries if required
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: INFO
    org.springframework.retry.support.RetryTemplate: DEBUG

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO

    # Set DEBUG level on Hystrix to get an error message when a fallback method is used.
    com.netflix.hystrix: DEBUG
    com.netflix.hystrix.strategy.properties.HystrixPropertiesChainedArchaiusProperty: WARN
    org.springframework.security: DEBUG
debug: true